name: Automatizar Imagenes a Google Sheets
on:
  schedule:
    - cron: '0 13 * * *' # 8:00 AM hora Perú
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # Permiso para publicar
      id-token: write   # Permiso de seguridad
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install pandas requests Pillow gspread oauth2client tqdm

      - name: Ejecutar procesamiento de imágenes
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: python generar_imagenes.py

      - name: Subir imágenes como Artefacto
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/' # Sube toda la carpeta docs (donde están las imágenes)

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2