name: Automatizar Imagenes a Google Sheets
on:
  schedule:
    - cron: '0 13 * * *' # 8:00 AM hora Perú
    - cron: '0 20 * * *' # 3:00 PM hora Perú
    - cron: '0 1 * * *'  # 8:00 PM hora Perú
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      
      id-token: write   
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install pandas requests Pillow gspread oauth2client tqdm

      - name: Ejecutar procesamiento de imágenes
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: python generar_imagenes.py

      - name: Subir imágenes como Artefacto
        uses: actions/upload-pages-artifact@v3 # Actualizado a v3 (compatible con v4 de artifacts)
        with:
          path: 'docs/' 

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Actualizado a v4