name: Automatizar Imagenes a Google Sheets

on:
  schedule:
    - cron: '07 05 * * *'  # 12:07 AM hora Perú
    - cron: '07 08 * * *'  # 03:07 AM hora Perú
    - cron: '07 11 * * *'  # 06:07 AM hora Perú
    - cron: '07 14 * * *'  # 09:07 AM hora Perú
    - cron: '07 17 * * *'  # 12:07 PM hora Perú
    - cron: '07 20 * * *'  # 03:07 PM hora Perú
    - cron: '07 01 * * *'  # 06:07 PM hora Perú
    - cron: '07 04 * * *'  # 09:07 PM hora Perú
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60 
    permissions:
      contents: write
      pages: write      
      id-token: write   
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Cache de imagenes
        uses: actions/cache@v4
        with:
          path: docs/images
          key: images-cache-${{ github.run_id }}
          restore-keys: |
            images-cache-

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests Pillow gspread oauth2client tqdm

      - name: Ejecutar procesamiento de imágenes
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: python generar_imagenes.py

      - name: Subir imágenes como Artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/' 

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4