name: Automatizar Imagenes a Google Sheets
on:
  schedule:
    - cron: '0 13 * * *' # 13:00 UTC es 8:00 AM Lima
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Descarga rápida (solo la última versión)

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install pandas requests Pillow gspread oauth2client tqdm

      - name: Ejecutar script
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: python generar_imagenes.py

      - name: Limpiar Historial y Subir Nuevas (Evita Saturar Almacenamiento)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          # Eliminamos imágenes viejas del índice de Git antes de subir nuevas
          git rm -r docs/images/*.jpg || echo "No hay fotos previas"
          git add docs/images/*.jpg
          git commit -m "Actualización diaria: $(date +'%Y-%m-%d')" || echo "Sin cambios"
          git push --force # Usamos force para sobreescribir y ahorrar espacio